#!/bin/bash


SNMP_STRING="public"
CHECK_SNMP_PLUGIN=/usr/lib/nagios/plugins/check_snmp
WATTS_OID=".1.3.6.1.4.1.1718.3.1.6.0"
TEMPERATURE_OID=".1.3.6.1.4.1.1718.3.2.5.1.6.1.1"
HUMIDITY_OID=".1.3.6.1.4.1.1718.3.2.5.1.10.1.1"

# Watts are in watts
WATTS_WARN=4250
WATTS_CRIT=4750

# Temperature is in Celcius and times 10 (40deg is 400)
TEMPERATURE_WARN_MAX=400
TEMPERATURE_WARN_MIN=100
TEMPERATURE_CRIT_MAX=450
TEMPERATURE_CRIT_MIN=50

# Humidity is in percentage
HUMIDITY_WARN_MAX=90
HUMIDITY_WARN_MIN=10
HUMIDITY_CRIT_MAX=95
HUMIDITY_CRIT_MIN=5

# Check Temperature SNMP call
# $USER1$/check_snmp -H $HOSTADDRESS$ -C $SNMP_STRING -o ".1.3.6.1.4.1.1718.3.2.5.1.6.1.1" -w 100:400 -c 50:450

# Check Humidity SNMP call
# $USER1$/check_snmp -H $HOSTADDRESS$ -C $SNMP_STRING -o ".1.3.6.1.4.1.1718.3.2.5.1.10.1.1" -w 10:90 -c 5:95

# Check Watts SNMP call
# $USER1$/check_snmp -H $HOSTADDRESS$ -C $SNMP_STRING -o ".1.3.6.1.4.1.1718.3.1.6.0" -w 4250 -c 4750

# Make sure the check_snmp plugin is available
if ! [ -f $CHECK_SNMP_PLUGIN ] ; then
  echo "CRIT: check_snmp not found at $CHECK_SNMP_PLUGIN"
  exit 2
fi
