#!/bin/bash


SNMP_STRING="public"
readonly CHECK_SNMP_PLUGIN=/usr/lib/nagios/plugins/check_snmp
readonly TOTAL_WATTS_MIB=".1.3.6.1.4.1.1718.3.1.6.0"
readonly TOWER_ONE_AMPS_MIB=".1.3.6.1.4.1.1718.3.2.2.1.7.1.1"
readonly TOWER_TWO_AMPS_MIB=".1.3.6.1.4.1.1718.3.2.2.1.7.2.1"
readonly TOWER_COUNT_MIB=".1.3.6.1.4.1.1718.3.1.4.0"
readonly SENSOR_COUNT_MIB=".1.3.6.1.4.1.1718.3.1.5.0"
readonly TEMPERATURE_SENSOR_A1_MIB=".1.3.6.1.4.1.1718.3.2.5.1.6.1.1"
readonly TEMPERATURE_SENSOR_A2_MIB=".1.3.6.1.4.1.1718.3.2.5.1.6.1.2"
readonly TEMPERATURE_SENSOR_B1_MIB=".1.3.6.1.4.1.1718.3.2.5.1.6.2.1"
readonly TEMPERATURE_SENSOR_B2_MIB=".1.3.6.1.4.1.1718.3.2.5.1.6.2.2"
readonly HUMIDITY_SENSOR_A1_MIB=".1.3.6.1.4.1.1718.3.2.5.1.10.1.1"
readonly HUMIDITY_SENSOR_A2_MIB=".1.3.6.1.4.1.1718.3.2.5.1.10.1.2"
readonly HUMIDITY_SENSOR_B1_MIB=".1.3.6.1.4.1.1718.3.2.5.1.10.2.1"
readonly HUMIDITY_SENSOR_B2_MIB=".1.3.6.1.4.1.1718.3.2.5.1.10.2.2"

# Watts are in watts
readonly WATTS_WARN=4250
readonly WATTS_CRIT=4750

# Load is in AMPs
readonly LOAD_ALARM=6

# Temperature is in Celcius 
TEMPERATURE_WARN_MAX=40
TEMPERATURE_WARN_MIN=10
TEMPERATURE_CRIT_MAX=45
TEMPERATURE_CRIT_MIN=50

# Humidity is in percentage
HUMIDITY_WARN_MAX=90
HUMIDITY_WARN_MIN=10
HUMIDITY_CRIT_MAX=95
HUMIDITY_CRIT_MIN=5

usage() {
  echo "Usage: $0 -H host -S <snmp string> [ -t ] [ -h ]"
  # TODO: add detailed help section here
  # TODO: need to add warning and critital levels, not just min/max
  exit 2;
}
CHECK_TEMPERATURE=false
CHECK_HUMIDITY=false
while getopts ":H:S:thw" opt; do
  case "${opt}" in
    H)
      PDU_HOST=${OPTARG}
      ;;
    S)
      SNMP_STRING=${OPTARG}
      ;;
    t)
      CHECK_TEMPERATURE=true
      ;;
    h)
      CHECK_HUMIDITY=true
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "${PDU_HOST}" ] ; then usage ; fi

# Make sure the check_snmp plugin is available
if ! [ -f $CHECK_SNMP_PLUGIN ] ; then
  echo "CRIT: check_snmp not found at $CHECK_SNMP_PLUGIN"
  exit 2
fi
# Make sure BC is installed, needed for comparison data
if ! [ $(which bc) ] ; then
  echo "CRIT: bc is required to do calculations, not in path"
  exit 2
fi

# Get the number of towers and sensor port count
get_tower_details() {
  local RAW_TOWER_CNT=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o "$TOWER_COUNT_MIB")
  readonly TOWER_CNT=$(echo $RAW_TOWER_CNT | cut -f 4 -d ' ')

  local RAW_SENSOR_CNT=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o "$SENSOR_COUNT_MIB")
  readonly SENSOR_CNT=$(echo $RAW_SENSOR_CNT | cut -f 4 -d ' ')
}

# This is the total watts used (combined if two towers)
get_power_consumed() {
  local RAW_TOTAL_WATTS=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o "$TOTAL_WATTS_MIB")
  readonly TOTAL_WATTS=$(echo $RAW_TOTAL_WATTS | cut -f 4 -d ' ')

  # This is the AMPs used, it is multiplied by 100 (5A is 500)
  # We will always check Tower 1
  local RAW_TOWER_ONE_FEED=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o "$TOWER_ONE_AMPS_MIB")
  readonly TOWER_ONE_FEED=$(echo $RAW_TOWER_ONE_FEED | cut -f 4 -d ' ')
  # Only check Tower 2 if the tower count is 2
  if [ "2" == $TOWER_CNT ] ; then
    local RAW_TOWER_TWO_FEED=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o "$TOWER_TWO_AMPS_MIB")
    readonly TOWER_TWO_FEED=$(echo $RAW_TOWER_TWO_FEED | cut -f 4 -d ' ')
  fi
}

check_power_thresholds() {
  # For now, we are going to use the ServerTech defaults

  # Check Watts (TODO)

  # Check AMPs
  local LOAD_ALARM_CONVERT=$(($LOAD_ALARM * 100))
  if [ $TOWER_ONE_FEED -gt $LOAD_ALARM_CONVERT ] ; then
    echo "Tower One Too High!"
  fi
  if [ $TOWER_TWO_FEED -gt $LOAD_ALARM_CONVERT ] ; then
    echo "Tower Two Too High!"
  fi
}

check_temperature_thresholds() {
  # do some checks here
  touch /dev/null
}

check_humidity_thresholds() {
  # do some checks here
  touch /dev/null
}

get_temperatures() {
  # if at least one tower has sensors, do detection
  if [ $SENSOR_CNT > 0 ] ; then
    local RAW_TEMP_A1=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o $TEMPERATURE_SENSOR_A1_MIB)
    local RAW_TEMP_A2=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o $TEMPERATURE_SENSOR_A2_MIB)
    readonly TEMP_A1=$(echo $RAW_TEMP_A1 | cut -f 4 -d ' ')
    readonly TEMP_A2=$(echo $RAW_TEMP_A2 | cut -f 4 -d ' ')
    if [ "2" == $SENSOR_CNT ] ; then
      local RAW_TEMP_B1=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o $TEMPERATURE_SENSOR_B1_MIB)
      local RAW_TEMP_B2=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o $TEMPERATURE_SENSOR_B2_MIB)
      readonly TEMP_B1=$(echo $RAW_TEMP_B1 | cut -f 4 -d ' ')
      readonly TEMP_B2=$(echo $RAW_TEMP_B2 | cut -f 4 -d ' ')
    else
      readonly TEMP_B1=-1
      readonly TEMP_B2=-1
    fi
  fi
}

get_humidity() {
  # if at least one tower has sensors, do detection
  if [ $SENSOR_CNT > 0 ] ; then
    local RAW_HUMIDITY_A1=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o  $HUMIDITY_SENSOR_A1_MIB)
    local RAW_HUMIDITY_A2=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o  $HUMIDITY_SENSOR_A2_MIB)
    readonly HUMIDITY_A1=$(echo $RAW_HUMIDITY_A1 | cut -f 4 -d ' ')
    readonly HUMIDITY_A2=$(echo $RAW_HUMIDITY_A2 | cut -f 4 -d ' ')
    if [ "2" == $SENSOR_CNT ] ; then
      local RAW_HUMIDITY_B1=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o $HUMIDITY_SENSOR_B1_MIB)
      local RAW_HUMIDITY_B2=$($CHECK_SNMP_PLUGIN -H $PDU_HOST -C $SNMP_STRING -o $HUMIDITY_SENSOR_B2_MIB)
      readonly HUMIDITY_B1=$(echo $RAW_HUMIDITY_B1 | cut -f 4 -d ' ')
      readonly HUMIDITY_B2=$(echo $RAW_HUMIDITY_B2 | cut -f 4 -d ' ')
    else
      readonly HUMIDITY_B1=-1
      readonly HUMIDITY_B2=-1
    fi
  fi
}

generate_performance_string() {
  local WATT_PERF="total_watts=$TOTAL_WATTS;$WATTS_WARN;$WATTS_CRIT"
  local TOWER_ONE_FEED_CONV=$(echo "scale=2; $TOWER_ONE_FEED/100" | bc)
  local TOWER_TWO_FEED_CONV=$(echo "scale=2; $TOWER_TWO_FEED/100" | bc)
  local TOWER_ONE_FEED_PERF="tower_one_amps=$TOWER_ONE_FEED_CONV;;$LOAD_ALARM"
  local TOWER_TWO_FEED_PERF="tower_one_amps=$TOWER_TWO_FEED_CONV;;$LOAD_ALARM"
  local TEMP_PERF=""
  local HUMIDITY_PERF=""

  if [ $CHECK_TEMPERATURE == "true" ] ; then
    local TEMP_A1_CONV=$(echo "scale=1; $TEMP_A1/10" | bc)
    local TEMP_A2_CONV=$(echo "scale=1; $TEMP_A2/10" | bc)
    local TEMP_B1_CONV=$(echo "scale=1; $TEMP_B1/10" | bc)
    local TEMP_B2_CONV=$(echo "scale=1; $TEMP_B2/10" | bc)
    local TEMP_RANGE_STRING="$TEMPERATURE_WARN_MAX;$TEMPERATURE_CRIT_MAX;0;100"
    if ! [ $TEMP_A1 == "-1" ] ; then
      local TEMP_PERF="temp_a1=$TEMP_A1_CONV;$TEMP_RANGE_STRING"
    fi
    if ! [ $TEMP_A2 == "-1" ] ; then
      local TEMP_PERF="$TEMP_PERF temp_a2=$TEMP_A2_CONV;$TEMP_RANGE_STRING"
    fi
    if ! [ $TEMP_B1 == "-1" ] ; then
      local TEMP_PERF="$TEMP_PERF temp_b1=$TEMP_B1_CONV;$TEMP_RANGE_STRING"
    fi
    if ! [ $TEMP_B2 == "-1" ] ; then
      local TEMP_PERF="$TEMP_PERF temp_b2=$TEMP_B2_CONV;$TEMP_RANGE_STRING"
    fi
  fi
  if [ $CHECK_HUMIDITY == "true" ] ; then
    local HUMIDITY_RANGE_STRING="$HUMIDITY_WARN_MAX;$HUMIDITY_CRIT_MAX;0;100"
    if ! [ $HUMIDITY_A1 == "-1" ] ; then
      local HUMIDITY_PERF="humidity_a1=$HUMIDITY_A1;$HUMIDITY_RANGE_STRING"
    fi
    if ! [ $HUMIDITY_A2 == "-1" ] ; then
      local HUMIDITY_PERF="$HUMIDITY_PERF humidity_a2=$HUMIDITY_A2;$HUMIDITY_RANGE_STRING"
    fi
    if ! [ $HUMIDITY_B1 == "-1" ] ; then
      local HUMIDITY_PERF="$HUMIDITY_PERF humidity_b1=$HUMIDITY_B1;$HUMIDITY_RANGE_STRING"
    fi
    if ! [ $HUMIDITY_B2 == "-1" ] ; then
      local HUMIDITY_PERF="$HUMIDITY_PERF humidity_b2=$HUMIDITY_B2;$HUMIDITY_RANGE_STRING"
    fi
  fi

  echo "$WATT_PERF $TOWER_ONE_FEED_PERF $TOWER_TWO_FEED_PERF"
  echo "$TEMP_PERF"
  echo "$HUMIDITY_PERF"
}

get_tower_details
get_power_consumed
if [ $CHECK_TEMPERATURE == "true" ] ; then
  get_temperatures
fi
if [ $CHECK_HUMIDITY == "true" ] ; then
  get_humidity
fi

check_power_thresholds
check_temperature_thresholds
check_humidity_thresholds

generate_performance_string
